apiVersion: v1
kind: Pod
metadata:
  name: simple-web-app
spec:
  containers:
  - name: webapp-color
    image: mmumshad/simple-webapp-color
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      value: "red"
