apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  capacity:
    storage: 1Gi
  # le champ volumeMode requiert l'activation de la "feature gate" Alpha BlockVolume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-pv
    type: DirectoryOrCreate
