apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress
  namespace: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
